### ISSUE TITLE
插件使用时出现 组件未找到 错误

### ISSUE THREAD

**Issue by leohowl** [tvfe/txv-miniprogram-plugin#6]
```
VM2052:1 jsEnginScriptError
Component is not found in path "pages/video/plugin:/wxa75efa648b60994b/video" (using by "pages/video/test")
Error: Component is not found in path "pages/video/plugin:/wxa75efa648b60994b/video" (using by "pages/video/test")
    at e (http://127.0.0.1:65140/appservice/__dev__/WAService.js:12:8473)
    at e (http://127.0.0.1:65140/appservice/__dev__/WAService.js:12:8625)
    at F (http://127.0.0.1:65140/appservice/__dev__/WAService.js:12:14589)
    at Object.t.addView (http://127.0.0.1:65140/appservice/__dev__/WAService.js:12:15599)
    at Function.value (http://127.0.0.1:65140/appservice/__dev__/WAService.js:14:6004)
    at I (http://127.0.0.1:65140/appservice/__dev__/WAService.js:13:17130)
    at W (http://127.0.0.1:65140/appservice/__dev__/WAService.js:13:19349)
    at U (http://127.0.0.1:65140/appservice/__dev__/WAService.js:13:19615)
    at Function.<anonymous> (http://127.0.0.1:65140/appservice/__dev__/WAService.js:13:21986)
    at http://127.0.0.1:65140/appservice/__dev__/WAService.js:13:27020
```
Demo在本地可以正常运行，但是在其他项目上测试时，在配置完成后出现“组件未找到”的错误。
app.json和子页面的.json配置文件使用了Demo中配置，测试代码亦是拷贝自Demo。已获得“腾讯视频”插件的许可。
造成这种问题的可能 的原因是什么？是我的配置文件出现问题，还是我漏掉了什么步骤

app.json
```
{
  "pages": [
    "pages/video/test"
  ],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#d03a3c",
    "navigationBarTitleText": "VIDEO",
    "navigationBarTextStyle": "white"
  },
  "networkTimeout": {
    "request": 30000,
    "connectSocket": 30000,
    "uploadFile": 30000,
    "downloadFile": 30000
  },
  "debug": true,
  "plugins": {
    "tencentvideo": {
      "version": "1.0.3",
      "provider": "wxa75efa648b60994b"
    }
  }
}
```

test.json (/pages/video/test)
```
{
  "usingComponents": {
    "txv-video": "plugin://tencentvideo/video"
  }
}
```

另test.wxml,test. wxss, test.js均为Demo代码

**Comment by zhai-conan** [comment]
同样的问题啊。就是无法找到组件

找不到playerid为txv1的txv-video组件;at pages/index/index page lifeCycleMethod onLoad function
Error: 找不到playerid为txv1的txv-video组件
